[workspace]
name = "ConservedWaterSearch"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64","linux-aarch64", "win-64"]

[dependencies]
numpy = ">=2.0.0"
matplotlib = "*"
nglview = "*"
scikit-learn = "*"
pytest = "*"
pip = "*"
uv = "*"

[feature.py311.dependencies]
python = "3.11.*"

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313.dependencies]
python = "3.13.*"

[feature.py314.dependencies]
python = "3.14.*"

[environments]
default = { features = ["py311"] }
py311 = { features = ["py311"] }
py312 = { features = ["py312"] }
py313 = { features = ["py313"] }
py314 = { features = ["py314"] }

[tasks]
