name: CI

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  pre-commit:
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout Code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        submodules: true
    - name: Create Python Environment
      uses: prefix-dev/setup-pixi@82d477f15f3a381dbcc8adc1206ce643fe110fb7
      with:
        pixi-version: v0.54.1
        cache: false
        environments: py311
        activate-environment: true
    - name: Install pre-commit
      run: python -m pip install pre-commit
    - name: Run pre-commit
      run: pre-commit run --all-files

  build:

    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        include:
          - python: "3.11"
            pixi-env: "py311"
          - python: "3.12"
            pixi-env: "py312"
          - python: "3.13"
            pixi-env: "py313"
          - python: "3.14"
            pixi-env: "py314"

    steps:
    - name: Checkout Code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        submodules: true
    - name: Create Python Environment
      uses: prefix-dev/setup-pixi@82d477f15f3a381dbcc8adc1206ce643fe110fb7
      with:
        pixi-version: v0.54.1
        cache: false
        environments: ${{ matrix.pixi-env }}
        activate-environment: true
    - name: Install package
      run: python -m pip install -e .
    - name: Run Tests
      run: pytest tests/ -v
